# Generated by Django 6.0.1 on 2026-01-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_attendee_email_alter_ticket_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
