# Generated by Django 6.0.1 on 2026-01-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_attendee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.attendee'),
        ),
    ]
