# Generated by Django 6.0.1 on 2026-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_ticket_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
