# Generated by Django 6.0.1 on 2026-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
    ]
